
import java.awt.Color;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


public class atmDeposit extends javax.swing.JFrame {

 
    
    public atmDeposit() {
        initComponents();
    }
    bankStorage bankDep = bankStorage.getInstance();
    atmProcess dp= new atmProcess();
    ImageIcon icon = new ImageIcon("check.png");
    ImageIcon info = new ImageIcon("info.png");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Jbackground = new javax.swing.JLabel();
        withdraw = new javax.swing.JButton();
        back = new javax.swing.JButton();
        deposit = new javax.swing.JButton();
        balance = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        withdraw1 = new javax.swing.JButton();
        withdraw2 = new javax.swing.JButton();
        balance1 = new javax.swing.JButton();
        enter1 = new javax.swing.JButton();
        balance2 = new javax.swing.JButton();
        BgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(419, 620));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setAutoscrolls(true);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 460, 61, 40);

        clear.setText("CLEAR");
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(290, 410, 90, 34);

        cancel.setText("CANCEL");
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(290, 360, 90, 34);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/6.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 410, 61, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(200, 354, 61, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(110, 356, 61, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(110, 410, 62, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9.png"))); // NOI18N
        jButton6.setAutoscrolls(true);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(200, 460, 62, 40);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(20, 355, 62, 40);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4.png"))); // NOI18N
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(20, 406, 61, 40);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/7.png"))); // NOI18N
        jButton9.setAutoscrolls(true);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(20, 460, 62, 40);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/10.png"))); // NOI18N
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton10MouseExited(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(110, 510, 60, 40);

        jPanel1.setLayout(null);

        Jbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/DEPOSIT (1).png"))); // NOI18N
        jPanel1.add(Jbackground);
        Jbackground.setBounds(0, 0, 270, 260);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 50, 270, 260);

        withdraw.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        withdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdrawMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                withdrawMouseExited(evt);
            }
        });
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });
        getContentPane().add(withdraw);
        withdraw.setBounds(10, 130, 50, 30);

        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(350, 250, 50, 30);

        deposit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deposit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depositMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                depositMouseExited(evt);
            }
        });
        deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositActionPerformed(evt);
            }
        });
        getContentPane().add(deposit);
        deposit.setBounds(10, 250, 50, 30);

        balance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        balance.setToolTipText("");
        balance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        balance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                balanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                balanceMouseExited(evt);
            }
        });
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });
        getContentPane().add(balance);
        balance.setBounds(350, 130, 50, 30);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empty.png"))); // NOI18N
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton11MouseExited(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(20, 510, 60, 40);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dot.png"))); // NOI18N
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton12MouseExited(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(200, 510, 60, 40);

        withdraw1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        withdraw1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withdraw1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdraw1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                withdraw1MouseExited(evt);
            }
        });
        withdraw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdraw1ActionPerformed(evt);
            }
        });
        getContentPane().add(withdraw1);
        withdraw1.setBounds(10, 210, 50, 30);

        withdraw2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        withdraw2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withdraw2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdraw2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                withdraw2MouseExited(evt);
            }
        });
        withdraw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdraw2ActionPerformed(evt);
            }
        });
        getContentPane().add(withdraw2);
        withdraw2.setBounds(10, 170, 50, 30);

        balance1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        balance1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        balance1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                balance1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                balance1MouseExited(evt);
            }
        });
        balance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balance1ActionPerformed(evt);
            }
        });
        getContentPane().add(balance1);
        balance1.setBounds(350, 210, 50, 30);

        enter1.setText("ENTER");
        enter1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enter1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enter1MouseExited(evt);
            }
        });
        enter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter1ActionPerformed(evt);
            }
        });
        getContentPane().add(enter1);
        enter1.setBounds(290, 460, 90, 34);

        balance2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        balance2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        balance2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                balance2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                balance2MouseExited(evt);
            }
        });
        balance2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balance2ActionPerformed(evt);
            }
        });
        getContentPane().add(balance2);
        balance2.setBounds(350, 170, 50, 30);

        BgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PIN BACKGROUND.png"))); // NOI18N
        getContentPane().add(BgImage);
        BgImage.setBounds(-20, -10, 490, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        
        
    }//GEN-LAST:event_clearActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        atmGUI home = new atmGUI();
        home.show();
        dispose();
        
    }//GEN-LAST:event_cancelActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
         
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
         
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
         
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
         
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
         
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        
         
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
          jButton7.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        jButton7.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        jButton4.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton4MouseEntered

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setBackground(Color.RED);
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_cancelMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        clear.setBackground(Color.ORANGE);
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        clear.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_clearMouseExited

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        jButton4.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        jButton3.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        jButton3.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        jButton8.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        jButton8.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        jButton5.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
        jButton9.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        jButton9.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        jButton6.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        jButton6.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
        jButton10.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton10MouseEntered

    private void jButton10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseExited
        jButton10.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton10MouseExited

    private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed
        
        
        
        double deposit100 = 100;
        double number = bankDep.getBal() + deposit100;
        bankDep.setBal(number);
        
        JOptionPane.showMessageDialog(null,"Successfully Deposited!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
        Object[] options = {"Yes",
                    "No"};
        
        int result = JOptionPane.showOptionDialog(null,
        "Would you like to deposit again?",
        "System Message",
        JOptionPane.YES_OPTION,
        JOptionPane.NO_OPTION,
        info,     //do not use a custom Icon
        options,  //the titles of buttons
        options[0]); //default button title
        
        if(result == 0){
            this.setVisible(false);
            new atmDeposit().setVisible(true);
            
        }
        else {
            this.setVisible(false);
            new atmProcess().setVisible(true);
        }
    }//GEN-LAST:event_withdrawActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
       double deposit2000 = 2000;
        double number = bankDep.getBal();
        number = number + deposit2000;
        bankDep.setBal(number);
        JOptionPane.showMessageDialog(null,"Successfully Deposited!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
        Object[] options = {"Yes",
                    "No"};
        Component frame = null;
        int result = JOptionPane.showOptionDialog(frame,
        "Would you like to deposit again?",
        "System Message",
        JOptionPane.YES_OPTION,
        JOptionPane.NO_OPTION,
        info,     //do not use a custom Icon
        options,  //the titles of buttons
        options[0]); //default button title
        
        if(result == 0){
            this.setVisible(false);
            new atmDeposit().setVisible(true);
            
        }
        else {
            this.setVisible(false);
            new atmProcess().setVisible(true);
        }
        
        
    }//GEN-LAST:event_balanceActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        atmProcess pro = new atmProcess();
        pro.show();
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionPerformed
        double deposit1000 = 1000;
        double number = bankDep.getBal();
        number = number + deposit1000;
        bankDep.setBal(number);
     
        JOptionPane.showMessageDialog(null,"Successfully Deposited!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
        Object[] options = {"Yes",
                    "No"};
        Component frame = null;
        int result = JOptionPane.showOptionDialog(frame,
        "Would you like to deposit again?",
        "System Message",
        JOptionPane.YES_OPTION,
        JOptionPane.NO_OPTION,
        info,     //do not use a custom Icon
        options,  //the titles of buttons
        options[0]); //default button title
        
        if(result == 0){
            this.setVisible(false);
            new atmDeposit().setVisible(true);
            
        }
        else {
            this.setVisible(false);
            new atmProcess().setVisible(true);
        }
    }//GEN-LAST:event_depositActionPerformed

    private void balanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceMouseEntered
        balance.setBackground(Color.GREEN);
    }//GEN-LAST:event_balanceMouseEntered

    private void balanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceMouseExited
        balance.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_balanceMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setBackground(Color.GREEN);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_backMouseExited

    private void depositMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMouseEntered
        deposit.setBackground(Color.GREEN);
    }//GEN-LAST:event_depositMouseEntered

    private void depositMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMouseExited
        deposit.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_depositMouseExited

    private void withdrawMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseEntered
        withdraw.setBackground(Color.GREEN);
    }//GEN-LAST:event_withdrawMouseEntered

    private void withdrawMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseExited
        withdraw.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_withdrawMouseExited

    private void jButton11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseEntered
        jButton10.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton11MouseEntered

    private void jButton11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseExited
        jButton10.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton11MouseExited

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseEntered

    private void jButton12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseExited

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void enter1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_enter1MouseEntered

    private void enter1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_enter1MouseExited

    private void enter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter1ActionPerformed
        
        
    }//GEN-LAST:event_enter1ActionPerformed

    private void withdraw1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdraw1MouseEntered
        withdraw1.setBackground(Color.GREEN);
    }//GEN-LAST:event_withdraw1MouseEntered

    private void withdraw1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdraw1MouseExited
        withdraw1.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_withdraw1MouseExited

    private void withdraw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdraw1ActionPerformed
        double deposit500 = 500;
        double number = bankDep.getBal() + deposit500;
        bankDep.setBal(number);
      
        JOptionPane.showMessageDialog(null,"Successfully Deposited!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
        Object[] options = {"Yes",
                    "No"};
        Component frame = null;
        int result = JOptionPane.showOptionDialog(frame,
        "Would you like to deposit again?",
        "System Message",
        JOptionPane.YES_OPTION,
        JOptionPane.NO_OPTION,
        info,     //do not use a custom Icon
        options,  //the titles of buttons
        options[0]); //default button title
        
        if(result == 0){
            this.setVisible(false);
            new atmDeposit().setVisible(true);
            
        }
        else {
            this.setVisible(false);
            new atmProcess().setVisible(true);
        }
    }//GEN-LAST:event_withdraw1ActionPerformed

    private void withdraw2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdraw2MouseEntered
        withdraw2.setBackground(Color.GREEN);
    }//GEN-LAST:event_withdraw2MouseEntered

    private void withdraw2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdraw2MouseExited
        withdraw2.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_withdraw2MouseExited

    private void withdraw2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdraw2ActionPerformed
       double deposit200 = 200;
        double number = bankDep.getBal() + deposit200;
        bankDep.setBal(number);
        JOptionPane.showMessageDialog(null,"Successfully Deposited!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
        Object[] options = {"Yes",
                    "No"};
        Component frame = null;
        int result = JOptionPane.showOptionDialog(frame,
        "Would you like to deposit again?",
        "System Message",
        JOptionPane.YES_OPTION,
        JOptionPane.NO_OPTION,
        info,     //do not use a custom Icon
        options,  //the titles of buttons
        options[0]); //default button title
        
        if(result == 0){
            this.setVisible(false);
            new atmDeposit().setVisible(true);
            
        }
        else {
            this.setVisible(false);
            new atmProcess().setVisible(true);
        }
    }//GEN-LAST:event_withdraw2ActionPerformed

    private void balance1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balance1MouseEntered
        balance1.setBackground(Color.GREEN);
    }//GEN-LAST:event_balance1MouseEntered

    private void balance1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balance1MouseExited
        balance1.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_balance1MouseExited

    private void balance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balance1ActionPerformed
        double deposit10000 = 10000;
        double number = bankDep.getBal();
        number = number + deposit10000;
        bankDep.setBal(number);
       
        JOptionPane.showMessageDialog(null,"Successfully Deposited!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
        Object[] options = {"Yes",
                    "No"};
        Component frame = null;
        int result = JOptionPane.showOptionDialog(frame,
        "Would you like to deposit again?",
        "System Message",
        JOptionPane.YES_OPTION,
        JOptionPane.NO_OPTION,
        info,     //do not use a custom Icon
        options,  //the titles of buttons
        options[0]); //default button title
        
        if(result == 0){
            this.setVisible(false);
            new atmDeposit().setVisible(true);
            
        }
        else {
            this.setVisible(false);
            new atmProcess().setVisible(true);
        }
    }//GEN-LAST:event_balance1ActionPerformed

    private void balance2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balance2MouseEntered
        balance2.setBackground(Color.GREEN);
    }//GEN-LAST:event_balance2MouseEntered

    private void balance2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balance2MouseExited
        balance2.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_balance2MouseExited

    private void balance2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balance2ActionPerformed
        double deposit5000 = 5000;
        double number = bankDep.getBal();
        number = number + deposit5000;
        bankDep.setBal(number);

        JOptionPane.showMessageDialog(null,"Successfully Deposited!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
        Object[] options = {"Yes",
                    "No"};
        Component frame = null;
        int result = JOptionPane.showOptionDialog(frame,
        "Would you like to deposit again?",
        "System Message",
        JOptionPane.YES_OPTION,
        JOptionPane.NO_OPTION,
        info,     //do not use a custom Icon
        options,  //the titles of buttons
        options[0]); //default button title
        
        if(result == 0){
            this.setVisible(false);
            new atmDeposit().setVisible(true);
            
        }
        else {
            this.setVisible(false);
            new atmProcess().setVisible(true);
        }
    }//GEN-LAST:event_balance2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frontatm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new atmDeposit().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BgImage;
    private javax.swing.JLabel Jbackground;
    private javax.swing.JButton back;
    private javax.swing.JButton balance;
    private javax.swing.JButton balance1;
    private javax.swing.JButton balance2;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    private javax.swing.JButton deposit;
    private javax.swing.JButton enter1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton withdraw;
    private javax.swing.JButton withdraw1;
    private javax.swing.JButton withdraw2;
    // End of variables declaration//GEN-END:variables
}
