import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


public class atmWithdraw extends javax.swing.JFrame {

    /**
     * Creates new form atm Withdraw
     */
    public atmWithdraw() {
        initComponents();
        
    }
    bankStorage bank = bankStorage.getInstance();
    
    ImageIcon icon = new ImageIcon("check.png");
    ImageIcon icon2 = new ImageIcon("JOPTION ICON LOGO.png");
    ImageIcon warning = new ImageIcon("warning.png");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        enter = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Jbackground = new javax.swing.JLabel();
        btn100 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        btn1k = new javax.swing.JButton();
        btn2k = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btn500 = new javax.swing.JButton();
        btn200 = new javax.swing.JButton();
        btn10k = new javax.swing.JButton();
        btn5k = new javax.swing.JButton();
        BgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(419, 620));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setAutoscrolls(true);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 460, 61, 40);

        enter.setText("ENTER");
        enter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enterMouseExited(evt);
            }
        });
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter);
        enter.setBounds(290, 460, 90, 34);

        clear.setText("CLEAR");
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(290, 410, 90, 34);

        cancel.setText("CANCEL");
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(290, 360, 90, 34);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/6.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 410, 61, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(200, 354, 61, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(110, 356, 61, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(110, 410, 62, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9.png"))); // NOI18N
        jButton6.setAutoscrolls(true);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(200, 460, 62, 40);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(20, 355, 62, 40);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4.png"))); // NOI18N
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(20, 406, 61, 40);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/7.png"))); // NOI18N
        jButton9.setAutoscrolls(true);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(20, 460, 62, 40);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/10.png"))); // NOI18N
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton10MouseExited(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(110, 510, 60, 40);

        jPanel1.setLayout(null);

        Jbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/WITHDRAW.png"))); // NOI18N
        jPanel1.add(Jbackground);
        Jbackground.setBounds(0, 0, 270, 260);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 50, 270, 260);

        btn100.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn100.setActionCommand("btn100");
        btn100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn100MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn100MouseExited(evt);
            }
        });
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });
        getContentPane().add(btn100);
        btn100.setBounds(10, 130, 50, 30);

        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setActionCommand("btnBack");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(350, 250, 50, 30);

        btn1k.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn1k.setActionCommand("btn1k");
        btn1k.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1kMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1kMouseExited(evt);
            }
        });
        btn1k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1kActionPerformed(evt);
            }
        });
        getContentPane().add(btn1k);
        btn1k.setBounds(10, 250, 50, 30);

        btn2k.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn2k.setActionCommand("btn2k");
        btn2k.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2kMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2kMouseExited(evt);
            }
        });
        btn2k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2kActionPerformed(evt);
            }
        });
        getContentPane().add(btn2k);
        btn2k.setBounds(350, 130, 50, 30);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empty.png"))); // NOI18N
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton11MouseExited(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(20, 510, 60, 40);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dot.png"))); // NOI18N
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton12MouseExited(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(200, 510, 60, 40);

        btn500.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn500.setActionCommand("btn500");
        btn500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn500MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn500MouseExited(evt);
            }
        });
        btn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500ActionPerformed(evt);
            }
        });
        getContentPane().add(btn500);
        btn500.setBounds(10, 210, 50, 30);

        btn200.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn200.setActionCommand("btn200");
        btn200.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn200.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn200MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn200MouseExited(evt);
            }
        });
        btn200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn200ActionPerformed(evt);
            }
        });
        getContentPane().add(btn200);
        btn200.setBounds(10, 170, 50, 30);

        btn10k.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn10k.setActionCommand("btn10k");
        btn10k.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn10k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn10kMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn10kMouseExited(evt);
            }
        });
        btn10k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10kActionPerformed(evt);
            }
        });
        getContentPane().add(btn10k);
        btn10k.setBounds(350, 210, 50, 30);

        btn5k.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn5k.setActionCommand("btn5k");
        btn5k.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn5kMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn5kMouseExited(evt);
            }
        });
        btn5k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5kActionPerformed(evt);
            }
        });
        getContentPane().add(btn5k);
        btn5k.setBounds(350, 170, 50, 30);

        BgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PIN BACKGROUND.png"))); // NOI18N
        getContentPane().add(BgImage);
        BgImage.setBounds(-20, -10, 490, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_enterActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_clearActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        atmGUI home = new atmGUI();
        home.show();
        dispose();
        
    }//GEN-LAST:event_cancelActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
          jButton7.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        jButton7.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        jButton4.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton4MouseEntered

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setBackground(Color.RED);
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_cancelMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        clear.setBackground(Color.ORANGE);
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        clear.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_clearMouseExited

    private void enterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseEntered
        enter.setBackground(Color.GREEN);
    }//GEN-LAST:event_enterMouseEntered

    private void enterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseExited
        enter.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_enterMouseExited

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        jButton4.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        jButton3.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        jButton3.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        jButton8.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        jButton8.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        jButton5.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
        jButton9.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        jButton9.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        jButton6.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        jButton6.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
        jButton10.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton10MouseEntered

    private void jButton10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseExited
        jButton10.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton10MouseExited
    double number;
    atmProcess wd= new atmProcess();
    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
        double withdraw100 = 100;
        if(bank.getBal() >= withdraw100){
            number = bank.getBal() - withdraw100;
            bank.setBal(number);
           
            JOptionPane.showMessageDialog(null,"Successfully Withdrawed!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
            JOptionPane.showMessageDialog(null,"THE BANK \n Account Number: 5432 8666 4232 1234 \n Amount: 100","RECEIPT",JOptionPane.PLAIN_MESSAGE,icon2);
            dispose();
            wd.show();
        }else{
        JOptionPane.showMessageDialog(null,"Not Enough Money!!","Alert",JOptionPane.PLAIN_MESSAGE,warning);
        
        }
    }//GEN-LAST:event_btn100ActionPerformed

    private void btn2kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2kActionPerformed
        double withdraw2000 = 2000;
        if(bank.getBal() >= withdraw2000){
            number = bank.getBal() - withdraw2000;
            bank.setBal(number);
            
            JOptionPane.showMessageDialog(null,"Successfully Withdrawed!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
            JOptionPane.showMessageDialog(null,"THE BANK \n Account Number: 5432 8666 4232 1234 \n Amount: 2000","RECEIPT",JOptionPane.PLAIN_MESSAGE,icon2);
            dispose();
            wd.show();
        }else{
        JOptionPane.showMessageDialog(null,"Not Enough Money!!","Alert",JOptionPane.PLAIN_MESSAGE,warning);
        }
    }//GEN-LAST:event_btn2kActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        atmProcess pro1 = new atmProcess();
        pro1.show();
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void btn1kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1kActionPerformed
        double withdraw1000 = 1000;
        if(bank.getBal() >= withdraw1000){
            number = bank.getBal() - withdraw1000;
            bank.setBal(number);
            
            JOptionPane.showMessageDialog(null,"Successfully Withdrawed!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
            JOptionPane.showMessageDialog(null,"THE BANK \n Account Number: 5432 8666 4232 1234 \n Amount: 1000","RECEIPT",JOptionPane.PLAIN_MESSAGE,icon2);
            dispose();
            wd.show();
        }else{
        JOptionPane.showMessageDialog(null,"Not Enough Money!!","Alert",JOptionPane.PLAIN_MESSAGE,warning);
        }
    }//GEN-LAST:event_btn1kActionPerformed

    private void btn2kMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2kMouseEntered
        btn2k.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn2kMouseEntered

    private void btn2kMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2kMouseExited
        btn2k.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btn2kMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setBackground(Color.GREEN);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_backMouseExited

    private void btn1kMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1kMouseEntered
        btn1k.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn1kMouseEntered

    private void btn1kMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1kMouseExited
        btn1k.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btn1kMouseExited

    private void btn100MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn100MouseEntered
        btn100.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn100MouseEntered

    private void btn100MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn100MouseExited
        btn100.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btn100MouseExited

    private void jButton11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseEntered
        jButton10.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton11MouseEntered

    private void jButton11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseExited
        jButton10.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jButton11MouseExited

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseEntered

    private void jButton12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseExited

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btn500MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn500MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn500MouseEntered

    private void btn500MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn500MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn500MouseExited

    private void btn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500ActionPerformed
        double withdraw500 = 500;
        if(bank.getBal() >= withdraw500){
            number = bank.getBal() - withdraw500;
            bank.setBal(number);
           
            JOptionPane.showMessageDialog(null,"Successfully Withdrawed!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
            JOptionPane.showMessageDialog(null,"THE BANK \n Account Number: 5432 8666 4232 1234 \n Amount: 500","RECEIPT",JOptionPane.PLAIN_MESSAGE,icon2);
            dispose();
            wd.show();
        }else{
        JOptionPane.showMessageDialog(null,"Not Enough Money!!","Alert",JOptionPane.PLAIN_MESSAGE,warning);
        }
    }//GEN-LAST:event_btn500ActionPerformed

    private void btn200MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn200MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn200MouseEntered

    private void btn200MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn200MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn200MouseExited

    private void btn200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn200ActionPerformed
        double withdraw200 = 200;
        if(bank.getBal() >= withdraw200){
            number = bank.getBal() - withdraw200;
            bank.setBal(number);
            
            JOptionPane.showMessageDialog(null,"Successfully Withdrawed!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
            JOptionPane.showMessageDialog(null,"THE BANK \n Account Number: 5432 8666 4232 1234 \n Amount: 200","RECEIPT",JOptionPane.PLAIN_MESSAGE,icon2);
            dispose();
            wd.show();
        }else{
        JOptionPane.showMessageDialog(null,"Not Enough Money!!","Alert",JOptionPane.PLAIN_MESSAGE,warning);
        }
    }//GEN-LAST:event_btn200ActionPerformed

    private void btn10kMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10kMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10kMouseEntered

    private void btn10kMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10kMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10kMouseExited

    private void btn10kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10kActionPerformed
        double withdraw10000 = 10000;
        if(bank.getBal() >= withdraw10000){
            number = bank.getBal() - withdraw10000;
            bank.setBal(number);
            
            JOptionPane.showMessageDialog(null,"Successfully Withdrawed!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
            JOptionPane.showMessageDialog(null,"THE BANK \n Account Number: 5432 8666 4232 1234 \n Amount: 10000","RECEIPT",JOptionPane.PLAIN_MESSAGE,icon2);
            dispose();
            wd.show();
        }else{
        JOptionPane.showMessageDialog(null,"Not Enough Money!!","Alert",JOptionPane.PLAIN_MESSAGE,warning);
        }
    }//GEN-LAST:event_btn10kActionPerformed

    private void btn5kMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5kMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5kMouseEntered

    private void btn5kMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5kMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5kMouseExited

    private void btn5kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5kActionPerformed
        double withdraw5000 = 5000;
        if(bank.getBal() >= withdraw5000){
            number = bank.getBal() - withdraw5000;
            bank.setBal(number);
            
            JOptionPane.showMessageDialog(null,"Successfully Withdrawed!!","System Message",JOptionPane.PLAIN_MESSAGE,icon);
            JOptionPane.showMessageDialog(null,"THE BANK \n Account Number: 5432 8666 4232 1234 \n Amount: 5000","RECEIPT",JOptionPane.PLAIN_MESSAGE,icon2);
            dispose();
            wd.show();
        }else{
         JOptionPane.showMessageDialog(null,"Not Enough Money!!","Alert",JOptionPane.PLAIN_MESSAGE,warning);  
        }
    }//GEN-LAST:event_btn5kActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frontatm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new atmWithdraw().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BgImage;
    private javax.swing.JLabel Jbackground;
    private javax.swing.JButton back;
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn10k;
    private javax.swing.JButton btn1k;
    private javax.swing.JButton btn200;
    private javax.swing.JButton btn2k;
    private javax.swing.JButton btn500;
    private javax.swing.JButton btn5k;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    private javax.swing.JButton enter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
